### ISSUE TITLE
Not sure why this is messing up...

### ISSUE THREAD

**Issue by philberhane** [samwize/python-email-crawler#20]
Traceback (most recent call last):
  File "email_crawler.py", line 12, in <module>
    logging.config.dictConfig(LOGGING)
  File "C:\Python27\lib\logging\config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Python27\lib\logging\config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'console': Cannot resolve 'ColorStreamHandler.ColorStreamHandler': No module named _curses

Can anyone help?

**Comment by philberhane** [comment]
Actually jk lol (I figured out how to install curses)
Now it's 
ValueError: Unable to configure handler 'console': tparm() argument 1 must be string, not None

**Comment by philberhane** [comment]
I've literally searched and changed every "None" in the code into a string with no results :/
