### ISSUE TITLE
ValueError: Unable to configure handler 'console': Cannot resolve 'ColorStreamHandler.ColorStreamHandler': No module named _curses

### ISSUE THREAD

**Issue by juragandotid** [samwize/python-email-crawler#22]
When i'm running it get an error :

Traceback (most recent call last):
  File "index.py", line 12, in <module>
    logging.config.dictConfig(LOGGING)
  File "C:\Python27\lib\logging\config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Python27\lib\logging\config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'console': Cannot resolve 'ColorStreamHandler.ColorStreamHandler': No module named _curses

**Comment by radzi00** [comment]
after: pip.exe install curses-2.2-cp27-none-win_amd64.whl
downloaded from:
https://download.lfd.uci.edu/pythonlibs/n1rrk3iq/curses-2.2-cp27-none-win_amd64.whl

I get the:
Traceback (most recent call last):
  File "email_crawler.py", line 12, in <module>
    logging.config.dictConfig(LOGGING)
  File "C:\Python27\lib\logging\config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Python27\lib\logging\config.py", line 576, in configure
    '%r: %s' % (name, e))
**ValueError: Unable to configure handler 'console': tparm() argument 1 must be string, not None**

**Comment by kjaz89** [comment]
we have the same issues?
  File "C:\Crawler\email_crawler.py", line 12, in <module>
    logging.config.dictConfig(LOGGING)
  File "C:\Python27\lib\logging\config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Python27\lib\logging\config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'console': Cannot resolve 'ColorStreamHandler.ColorStreamHandler': No module named _curses

**Comment by MarcoCiaramella** [comment]
fixed disabling logging configuration in email_crawler.py and adding custom configuration

```
from settings import LOGGING
import logging, logging.config
from logging.handlers import TimedRotatingFileHandler
from logging.handlers import RotatingFileHandler
import urllib, urllib2
import re, urlparse
import traceback
from database import CrawlerDb

# Debugging
# import pdb;pdb.set_trace()

# Logging
#logging.config.dictConfig(LOGGING)
logger = logging.getLogger("crawler_logger")
logger.setLevel(logging.INFO)
handler = TimedRotatingFileHandler('log','midnight',1,30)
formatter = logging.Formatter('%(asctime)s %(name)-2s %(levelname)-2s %(message)s','%y-%m-%d %H:%M:%S')
handler.setFormatter(formatter)
logger.addHandler(handler)
```
